### ISSUE TITLE
ImportError: No module named 'urllib2'

### ISSUE THREAD

**Issue by vanrijn** [noahcoad/SublimeGoogleSpellCheck#12]
I'm running Sublime Text 3 build 3059 and I just installed Google Spell Check and I see this error in the console view:

reloading plugin Google Spell Check.google-spell-check
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "google-spell-check in /Users/ME/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 4, in <module>
ImportError: No module named 'urllib2'

**Comment by evandrocoan** [comment]
I was on the branch master, which contains some unknown version. Switched to the branch st3 fixed the problem.

**Comment by noahcoad** [comment]
Thank you for the feedback. Sorry for the super long delay to address these! The plugin is now Python 3 / ST4-only -- `urllib2` is gone, it uses `urllib.request`. I believe they're fixed now. Please re-open if otherwise.
