### ISSUE TITLE
'str' object has no attribute 'parser'

### ISSUE THREAD

**Issue by mrjoshuak** [noahcoad/SublimeGoogleSpellCheck#13]
At some point in the last couple of months this stopped working for me.  Not sure it's a conflicting new packing or a change in the plugin, but it did work before.  Now when I run the command I get the expected pause, but the word is not corrected and I get this traceback in the console.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "google-spell-check in /Users/joshua/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 16, in run
  File "google-spell-check in /Users/joshua/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 23, in correct
AttributeError: 'str' object has no attribute 'parser'
```

**Comment by noahcoad** [comment]
Thank you for the feedback. Sorry for the super long delay to address these! The plugin has since been rewritten -- it no longer scrapes Google's search results page, it uses Google's JSON autocomplete endpoint instead, which removes this whole class of failure. The `HTMLParser` call this died on no longer exists. I believe they're fixed now. Please re-open if otherwise.
