### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Large

### ISSUE THREAD

**Issue by alexgorbatchev** [noahcoad/SublimeGoogleSpellCheck#6]
``` python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "google-spell-check in /Users/alexgorbatchev/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 16, in run
  File "google-spell-check in /Users/alexgorbatchev/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 22, in correct
  File "google-spell-check in /Users/alexgorbatchev/Library/Application Support/Sublime Text 3/Installed Packages/Google Spell Check.sublime-package", line 47, in get_page
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 479, in open
  File "X/urllib/request.py", line 591, in http_response
  File "X/urllib/request.py", line 517, in error
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 599, in http_error_default
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Large
```

My file is less than half a page long.

**Comment by noahcoad** [comment]
Thank you for the feedback. Sorry for the super long delay to address these! The plugin has since been rewritten -- it no longer scrapes Google's search results page, it uses Google's JSON autocomplete endpoint instead, which removes this whole class of failure. Request size is also capped now, so the URI can't grow large enough to 414. I believe they're fixed now. Please re-open if otherwise.

**Comment by alexgorbatchev** [comment]
Wow, it's been a minute since I filed that 😆
