### ISSUE TITLE
Does not work on ST3 with Linux (Fedora 20 here)

### ISSUE THREAD

**Issue by asfaltboy** [noahcoad/SublimeGoogleSpellCheck#9]
Seems the extension is attempting an HTTP request using a https url, which requires Python built with SSL support. Unfortunately, the interpreter embedded in ST3 does not seem to support SSL.

Is it possible to use Google Spell Check using http requests (without SSL) ?

here is the relevant traceback from st3 console:

```
Traceback (most recent call last):
  File "/home/pavel/Apps/st3/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "google-spell-check in /home/pavel/.config/sublime-text-3/Installed Packages/Google Spell Check.sublime-package", line 16, in run
  File "google-spell-check in /home/pavel/.config/sublime-text-3/Installed Packages/Google Spell Check.sublime-package", line 22, in correct
  File "google-spell-check in /home/pavel/.config/sublime-text-3/Installed Packages/Google Spell Check.sublime-package", line 47, in get_page
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 479, in open
  File "X/urllib/request.py", line 591, in http_response
  File "X/urllib/request.py", line 511, in error
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 696, in http_error_302
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 496, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1314, in unknown_open
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by rhoconlinux** [comment]
Hi everyone, same here. Ubuntu-Gnome 14.04.2. It doesn't work. 
@mlk5060 I modified the line 22 without success... nothing changes. :(

**Comment by mlk5060** [comment]
I've noticed that its stopped working for me lately.  Have given up using it.

**Comment by noahcoad** [comment]
mlk5060, thanks, i'll integrate the pull request

**Comment by afcuttin** [comment]
I concur (ubuntu 12.04 and ST 3)

**Comment by noahcoad** [comment]
Thank you for the feedback. Sorry for the super long delay to address these! The plugin is now ST4-only, and ST4's bundled Python has SSL support, so the https request works. I believe they're fixed now. Please re-open if otherwise.
